route:
        #    receiver: 'slack'
    receiver: 'email'

receivers:
        #    - name: 'slack'
        #      slack_configs:
        #          - send_resolved: true
        #            username: '<username>'
        #            channel: '#<channel-name>'
        #            api_url: '<incomming-webhook-url>'
    - name: 'email'
      email_configs:
          - send_resolved: true
            to: admin@liquibrium.com
            from: admin@liquibrium.com
            smarthost: smtp.mailgun.org:587
            auth_username: postmaster@mail.liquibrium.com
            auth_password: f31b3637d494e42abb9627b70abd3993-c1fe131e-7bb72076
            hello: alertmanager.liquibrium.local
