version: '3.4'

services:

  app:
    image: prom/prometheus
    container_name: prometheus-app
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ${DATA_DIR}/prometheus:/prometheus:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - cadvisor
    restart: always
    env_file:
      - ./prometheus.env
    networks:
      operations_intranet:
        ipv4_address: 172.34.7.2
        aliases:
          - prometheus

  node-exporter:
    image: prom/node-exporter
    container_name: prometheus-node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    restart: always
    deploy:
      mode: global
    env_file:
      - ./prometheus.env
    networks:
      operations_intranet:
        ipv4_address: 172.34.7.3

  alertmanager:
    image: prom/alertmanager
    container_name: prometheus-alertmanager
    volumes:
      - "./alertmanager/:/etc/alertmanager/"
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--cluster.advertise-address=172.34.7.4:9093'
    env_file:
      - ./prometheus.env
    networks:
      operations_intranet:
        ipv4_address: 172.34.7.4

  cadvisor:
    image: google/cadvisor
    container_name: prometheus-cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    deploy:
      mode: global
    env_file:
      - ./prometheus.env
    networks:
      operations_intranet:
        ipv4_address: 172.34.7.5

  grafana:
    image: grafana/grafana
    container_name: prometheus-grafana
    depends_on:
      - app
    volumes:
      - ${DATA_DIR}/grafana:/var/lib/grafana:rw
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/ldap.toml:/etc/grafana/ldap.toml
    env_file:
      - ./grafana/config.monitoring
    restart: always
    env_file:
      - ./prometheus.env
    networks:
      operations_intranet:
        ipv4_address: 172.34.7.6

  grafana-proxy-internal:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: prometheus-grafana-proxy-internal
    depends_on:
      - grafana
    environment:
      VIRTUAL_HOST: monitor.finsec.localdomain
      NETWORK_ACCESS: internal
    volumes:
      - ./grafana-nginx.conf:/etc/nginx/nginx.conf
    networks:
      operations_intranet:
        ipv4_address: 172.34.7.7
        aliases:
         - monitor.finsec
         - monitor

  app-proxy-internal:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: prometheus-app-proxy-internal
    depends_on:
      - app
    environment:
      VIRTUAL_HOST: prometheus.finsec.localdomain
      NETWORK_ACCESS: internal
    volumes:
      - ./app-nginx.conf:/etc/nginx/nginx.conf
    networks:
      operations_intranet:
        ipv4_address: 172.34.7.8
        aliases:
          - prometheus.finsec

  node-stats-proxy-internal:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: prometheus-node-stats-proxy-internal
    depends_on:
      - node-exporter
    environment:
      VIRTUAL_HOST: node-stats.finsec.localdomain
      NETWORK_ACCESS: internal
    volumes:
      - ./node-stats-nginx.conf:/etc/nginx/nginx.conf
    networks:
      operations_intranet:
        ipv4_address: 172.34.7.9

  alertmanager-proxy-internal:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: prometheus-alertmanager-proxy-internal
    depends_on:
      - alertmanager
    environment:
      VIRTUAL_HOST: alertmanager.finsec.localdomain
      NETWORK_ACCESS: internal
    volumes:
      - ./alertmanager-nginx.conf:/etc/nginx/nginx.conf
    networks:
      operations_intranet:
        ipv4_address: 172.34.7.10

  cadvisor-proxy-internal:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: prometheus-cadvisor-proxy-internal
    depends_on:
      - cadvisor
    environment:
      VIRTUAL_HOST: cadvisor.finsec.localdomain
      NETWORK_ACCESS: internal
    volumes:
      - ./cadvisor-nginx.conf:/etc/nginx/nginx.conf
    networks:
      operations_intranet:
        ipv4_address: 172.34.7.11

  alertmanager-bot:
    image: metalmatze/alertmanager-bot:0.4.0
    container_name: prometheus-alertmanager-bot
    environment:
      ALERTMANAGER_URL: http://prometheus-alertmanager:9093
      BOLT_PATH: /data/bot.db
      STORE: bolt
      TEMPLATE_PATHS: /templates/default.tmpl
    env_file:
      - ./prometheus.env
    volumes:
      - ${DATA_DIR}/alertmanager-bot:/data
    networks:
      operations_intranet:
        ipv4_address: 172.34.7.12

  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: prometheus-blackbox-exporter
    volumes:
      - ./blackbox-exporter:/config
    command:
      - '--config.file=/config/blackbox.yml'
    depends_on:
      - app
    restart: always
    env_file:
      - ./prometheus.env
    networks:
      operations_intranet:
        ipv4_address: 172.34.7.13

  blackbox-exporter-proxy-internal:
    image: registry.finsec.localdomain/proxy-nginx
    container_name: prometheus-blackbox-exporter-proxy-internal
    depends_on:
      - blackbox-exporter
    environment:
      VIRTUAL_HOST: blackbox-exporter.finsec.localdomain
      NETWORK_ACCESS: internal
    volumes:
      - ./blackbox-exporter-nginx.conf:/etc/nginx/nginx.conf
    networks:
      operations_intranet:
        ipv4_address: 172.34.7.14

networks:
  operations_intranet:
    external: true
