# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'finsec'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "prometheus-alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    static_configs:
    - targets:
      - "localhost:9090"

  - job_name: 'cadvisor'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.prometheus-cadvisor'
      type: 'A'
      port: 8080

    static_configs:
    - targets: ['prometheus-cadvisor:8080']

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.prometheus-node-exporter'
      type: 'A'
      port: 9100
    
    static_configs:
    - targets: ['prometheus-node-exporter:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io    # Target to probe with http.
#operations
        - https://dns.finsec.localdomain
        - https://registry.finsec.localdomain/v2
        - https://ca.finsec.localdomain
        - https://operations.finsec.localdomain
        - https://errors.finsec.localdomain
#bitwarden          
        - https://keychain.finsec.localdomain
#debug          
        - https://browser.finsec.localdomain
#directory
        - https://directory.finsec.localdomain
        - https://password.finsec.localdomain
#gitlab
        - https://vcsdb.finsec.localdomain
        - https://vcs.finsec.localdomain
        - https://packages.finsec.localdomain
        - https://dashboard.finsec.localdomain
        - https://browser.containers.finsec.localdomain
        - https://containers.finsec.localdomain/v2
        - https://diagram.finsec.localdomain
          #        - https://projects.finsec.localdomain TBD
#helpdesk
        - https://helpdesk.finsec.localdomain
        - https://helpdeskdb.finsec.localdomain
#firefox
        - https://sync.finsec.localdomain
#limesurvey          
        - https://surveydb.finsec.localdomain
        - https://survey.finsec.localdomain
#management
        - https://browser.registry.finsec.localdomain
        - https://portainer.finsec.localdomain          
#matomo          
        - https://trackingdb.finsec.localdomain
        - https://tracking.finsec.localdomain
#mattermost          
        - https://chatdb.finsec.localdomain
        - https://chat.finsec.localdomain
#minio
#        - https://storage.finsec.localdomain  # s3 protocol
        - https://console.storage.finsec.localdomain
#prometheus          
        - https://blackbox-exporter.finsec.localdomain
        - https://monitor.finsec.localdomain
        - https://prometheus.finsec.localdomain
        - https://node-stats.finsec.localdomain
        - https://alertmanager.finsec.localdomain
        - https://cadvisor.finsec.localdomain
#nextcloud          
        - https://clouddb.finsec.localdomain
        - https://cloudb.finsec.localdomain
        - https://cloudredis.finsec.localdomain
        - https://cloud.finsec.localdomain
        - https://office.finsec.localdomain
        - https://draw.finsec.localdomain
#openproject
        - https://tasks.finsec.localdomain
#external
        - https://explorer.bitcoin.finsec.localdomain
        - https://ronin.bitcoin.finsec.localdomain          
        - https://dojo.bitcoin.finsec.localdomain       
        - https://specter.bitcoin.finsec.localdomain 
#external(ravage)          
        - https://umbrel.bitcoin.finsec.localdomain
        - https://mempool.bitcoin.finsec.localdomain
        - https://backup.explorer.bitcoin.finsec.localdomain
        - https://pay.bitcoin.finsec.localdomain
        - https://terminal.lightning.finsec.localdomain
        - https://lnbits.lightning.finsec.localdomain
        - https://rtl.lightning.finsec.localdomain
        - https://backup.dojo.bitcoin.finsec.localdomain
        - https://thunderhub.lightning.finsec.localdomain
        - https://backup.specter.bitcoin.finsec.localdomain 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-blackbox-exporter:9115  # The blackbox exporter's real hostname:port.

